version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-default***REMOVED***}
      MYSQL_DATABASE: photo_uploads
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    environment:
      MYSQL_PASSWORD: ***REMOVED***  # Här anger du lösenordet
    command: flask run --host=0.0.0.0
    volumes:
      - /var/www/rpctid/uploads:/var/www/rpctid/uploads
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: